---
title: Section Two
header-includes:
   - \usepackage{cleveref}
   - \input{../symbols.tex}
---

# Background

Reliable prediction of bus arrival times requires up-to-date or *real-time* information about current traffic conditions @citep:Jeong_2005,cn;. This is, however, rarely available in the context of public transport data. @citet:Elliott_2020; present a general method of using static and real-time GTFS data to estimate vehicle speeds along roads as a proxy for estimating traffic conditions. Their work provides the basic for this current work, which uses the real-time network state to make predictions of bus arrival which account for traffic conditions.

In this section, we provide a review of the work by @cite:Elliott_2020;, and give some extra details on another major source of uncertainty: intermediary bus stops. Finally, we introduce the particle filter, describe its implementation, and discuss why it proves beneficial for predicting vehicle arrival times reliably.


## Estimating real-time road state

It is well documented in the transit research literature that one of the key pieces of information requied for accurate arrival time prediction is *real-time traffic conditions* @citep:cn;. Unfortunately, this information is largely difficult or impossible to obtain, making globally applicable prediction methods hard to come by. However, there does exist a standard for transit data, GTFS @citep:GoogleDevelopers_2006;, wihch is used globally---a prediction system derived from GTFS would thus be useful on a worldwide scale.

The general process implemented by @citet:Elliott_2020; consists of three components. The first involves using the available GTFS information to construct a *transit network* consisting of *nodes* (stops or intersections) and *edges* (the roads connecting them). The key point is that sections of each route can be mapped to their physical road, allowing traffic information to be obtained *independent* of the route. Next vehicles are modelled as they travel along their respective routes using real-time GTFS data, from which we estimate their *average speed along each road*. Finally the individual,likely noisy, speed 'observations' are used to update the underlying *road state*, which is what we will be using in \cref{predicting-arrival-time} to predict arrival time.


### GTFS network

TO DO: trim this down

The general structure of transit data has remained fairly standard, tracing back to an initial prescription by @citet:Cathey_2003;. This work introduced terms such as *trip* and *route*, which are continually used today. However, the stucture of the data was massively formalised in 2006 when Google released their first version of *General Transit Feed Specification (GTFS)* @citep:GoogleDevelopers_2006;.

Transit data requires information about *routes*, journeys from an origin to a destination servicing a sequence of *stops* where passengers may board or disembark, and *trips* which are time-specific instances of a route. The path or *shape* travelled by the vehicle is described by a sequence of GPS coordinates. This information is contained within *GTFS static* along with other information one might find on a printed timetable, such as scheduled arrival and departures.

Real-time transit data, on the other hand, includes information about the position of a vehicle. This might be in the form of a *distance travelled* along the route @citep:Wall_1999,Dailey_2001; or, more commonly in modern systems, as GPS coordinates (latitude and longitude) @citep:Cathey_2003,Hans_2015;. The structure and format of this information is described by *GTFS-realtime*.

An important aspect missing from the setup, however, is information about *physical interactions* between separate routes (which may share common roads) which is critical to accurate prediction @citep:Jeong_2005;. @citet:Elliott_2020; describe a simple process for combining route information from static GTFS data to obtain a *transit road network*, expressing each route as a sequence of physical roads. The benefit of this is that vehicles servicing different routes but using the same road(s) can share information about their speed. This greatly enhances the amount of data available for forecasting arrival times.

```{r road_nw,echo=FALSE}
# figure for the network
```

In the approach, stops are considered *nodes* in the network, while the roads between them are *edges*. Any buses travelling between the same two (or more) stops share the road between them, thus providing information about the speeds. This increases the rate of update and is particularly beneficial for predicting arrival times for low-frequency routes (see \cref{predicting-arrival-time}).
[mentioned in subsection intro]


### Particle filter estimates of road speeds

* introduce the recursive estimation of states in real-time
* describe the basic model: predict state, compare to observation, update state
* why the pf is well suited to buses (multimodality, etc)
* how the pf works (very, very simply) -> details in section 2.3
* added bonus: easy likelihood (Elliott & Lumley)
* another bonus: each particle records its travel time along road of known length -> average speed *distribution* (according to particles)
* can't really do this with, say, a Kalman filter


### Real-time network state model

* another recursive state estimation problem
* this time a Gaussian makes sense (single mode, usually)
* KF: proven way of estimating network state (Jeong? and some others ...?)
* much simpler estimation procedure: just some matrix calculations
* input: noisy 'observations' of vehicle speeds
* complication: vehicles travel with different speeds, between-vehicle variance, but want to estimate this *separately* from uncertainty of the mean
* B ~ Normal(beta, (Delta*q)^2 + Psi) (assume independence)
* these estimated from historical data (see section 3)
* since we're allowing multiple vehicles to travel simultaneously, Elliott & Lumley used Information filter - becomes a simple addition problem (add new information to current)


## Modelling uncertainty at bus stops


## Prediction using a particle filter

* @citet:Hans_2015; paper
* light details of how it works: how 'state' is pepresented

## OLD

## Recursive Bayes and particle filtering - skip?

In a real-time application, performing a full update of the posterior distribution of some parameters becomes hugely inefficient. It is possible to recursively update the posterior, however, by way of recursive Bayesian filtering (alternatively called sequential Monte Carlo). Given a random variable $\vec x = \vec x_{0:k} = \tvec{\vec x_0,\vec x_1,\ldots\,\vec x_k}$ at time $t_k$ following a Markov process with associated observation $\vec y = \vec y_{1:k} = \tvec{\vec y_1,\ldots,\vec y_k}$, the posterior distribution at time $t_k$ is expressed via the recursive formula
\[
p(\vec x_{0:k}\cond{} \vec y_{1:k}) \propto
   p(\vec x_{0:k-1}\cond{} \vec y_{1:k-1})
   p(\vec x_k\cond{}\vec x_{k-1})
   p(\vec y_k\cond{}\vec x_k)
\]
which involves the previous state, next state prediction, and the likelihood, respectively. We therefore need to compute $p(\vec x_k\cond{}\vec x_{k-1})$, which involves the *transition function* between consecutive states, and the likelihood $p(\vec y_k\cond{}\vec x_k)$. The specific details of each of these depends on the model, which is discussed in \cref{estimating-road-state-from-vehicle-observations}.


Estimation of recursive Bayesian models takes many forms, most notably the Kalman filter @citep:kf; which has been widely used in transit modelling @citep:Wall_1999,Dailey_2001,Cathey_2003,Jeong_2005;. However, as discussed by @citet:Hans_2015,Elliott_2020;, it makes several assumptions which do not work so well with transit vehicles, namely that the errors are normal with a single mode. The particle filter @citep:Gordon_1993; provides a numerical approach to solving recursive Bayesian models, much the same as Markov chain Monte Carlo provides estimates of standard posterior distributions. In a particle filter, the state $\vec x_k$ is represented by a sample of $N$\ particles $\{\vec x_k\vi\}_{i=1}^N$ with associated weights $\{w_k\vi\}_{i=1}^N$. We use the delta measure $\delta$ to express the approximated state
\[
   p(\vec x_{k-1} | \vec y_{0:k-1}) \approx \sum_{i=1}^N w_{k-1}^{(i)} \DiracMeasure{\vec x_{k-1}^{(i)}}{\vec x_{k-1}}.
\]

Particle filter estimates are updated in two steps. First the state prediction of $p(\vec x_k\cond{}\vec x_{k-1})$ is made using the transition function $f$, which implements the vehicle model (\cref{vehicle-model}):
\[
   p(\vec x_{k} | \vec x_{k-1}) \approx
      \sum_{i=1}^N w_{k-1}^{(i)}
         \DiracMeasure{\vec x_{k}^{(i)}}{\vec x_{k}},\quad
   \vec x_k\vi = f(\vec x_{k-1}\vi, \Delta_k, \sigma).
\]

Second is the likelihood update, which quantifies the probability of the observed vehicle position given each of the particle predictions. The particle weights are updated according to their likelihood,
\[
w_k\vi =
   \frac{w_{k-1}\vi p(\vec y_k\cond{}\vec x_k\vi)}{
      \sum_{j=1}^N w_{k-1}\vi[j] p(\vec y_k\cond{}\vec x_k\vi[j])
   }.
\]
For the likelihood function itself, we use an exponential distribution on the geographic distance between the particle and the observed location, as proposed by @citet:Elliott_2020;.

To ensure the *effective sample size* remains adequately large (greater than $\frac{1}{4}N)$, importance resampling of the particles, with replacemnet, is performed whenever the effective sample size $N_{\text{eff}} = \frac{1}{\sum_{i=1}^N (w_k\vi)^2}$ drops below the threshold. The particle filter was for this reason originally called the *bootstrap filter* @citep:Gordon_1993;.


## Estimating road state from vehicle observations

In a transit setup, we observe vehicle locations $\vec y_k$ consisting of the vehicle's latitude and longitude at time $t_k$. The goal is to estimate the vehicle's distance travelled $x$ and speed $\dot x$, from which we can calculate its average speed along individual road segments. The underlying, unobservable state of the vehicle is $\vec x_k = \tvec{x_k,\dots x_k}$.

Estimation of network state involves three steps: vehicle state estimation, estimation of average speed along roads, and updating the network state model.


### Vehicle model

Estimating vehicle state requires a vehicle model consisting of several key behaviours. @cite:Elliott_2020; give details, however of particular importance to arrival time prediction is the *dwell time* model for stop behaviour. When the bus arrives at a stop, it can either drive past, or stop and allow passengers to board and disembark. The model presented here is based directly off that described by @cite:Elliott_2020;, which is itself based of the model described by @cite:Hans_2015;.

When a bus approaches a bus stop, it stops with probability $\pi$ to pick up and drop off passengers. If there are no passengers, the vehicle does not stop and loses no time. However, if it does stop, the time lost doing so is referred to as *dwell time*. Dwell time is composed of two parts:

1. deceleration, doors open and close, acceleration; and
2. servicing passengers

The first is assumed constant for all stops, and is parameterised as $\gamma$, the *minimum dwell time*. The stop service time is given a distribution for each stop. The mean and variance of dwell time at stop $j$, estimated from historical data, are $\tau_j$ and $\omega_j$, respectively. The distribution is assumed to follow a (truncated) normal distribution,
\[
d_j \sim \TNormal{\tau_j}{\omega_j^2}{0}{\infty}.
\]
The total dwell time for a particle is
\[
z_j\vi = p\vi\left(\gamma + d_j\vi \right),\quad
p\vi \sim \Bern{\pi}.
\]
The dwell time model will be used in the arrival time prediction framework described in [[section 3]].


### Travel time estimation

The goal of the vehicle model is to estimate not only their real-time state (including speed), but also to estimate their *average speed along individual road segments*. How this is done will depend upon the estimation technique being used, and in some cases will not be possible. The particle filter, however, enables easy estimation of many additional parameters, including average speed along roads @citep:Elliott_2020;.

For each particle, the average speed (m/s) is calculated by first computing the *travel time* (seconds) along each road segment. To do so, the application stores each particle's start and end times, $T_{\ell}$ and $T'_{\ell}$, respectively, along segment $\ell$ of the route. This is easily accomplished due to the particle filter's iterative nature. The average speed of a particle along a road segment of length $\Tseglen_\ell$ is simply
\[
\Vttobs_\ell\vi =
   \frac{\Tseglen_\ell}{{T'}_\ell\vi - T_\ell\vi}.
\]

As with the vehicle state, the vehicle's posterior distribution of average speed is estimated from the particles using the delta measure,
\[
p(\Vttobs_\ell\cond{}\Vstate_{0:k},\Vobs_{1:k}) \approx
   \sum_{i=1}^N w_k\vi \DiracMeasure{\Vttobs_\ell}{\Vttobs_\ell\vi},
\]
from which the mean $\bar\NWobs_\ell$ and variance $\NWerr_\ell^2$ may be computed:
\begin{equation*}
\begin{split}
\bar\NWobs_\ell &=
   \E{\Vttobs_\ell\cond{}\Vstate_{0:k},\Vobs_{1:k}} =
   \sum_{i=1}^N w_k\vi \Vttobs_\ell\vi,\\
\NWerr_\ell^2 &=
   \Var{\Vttobs_\ell\cond{}\Vstate_{0:k},\Vobs_{1:k}} =
   \sum_{i=1}^N w_k\vi \left(\Vttobs_\ell - \bar\NWobs_\ell\vi\right)^2.
\end{split}
\end{equation*}
These can be used in the next step to update the network state.


### Network state update

The network state model described by @citet:Elliott_2020; expresses the vehicle speed along roads using a hierarchical structure consisting of: the underlying, average speed $\RouteNWstateseg_{\ellc}$ of vehicles travelling along a road $\ell$ at time $c$ with uncertainty $\NWstatevar_{\ellc}$; the variance $\NWvar_\ell$ between individual vehicles $m\in V_m$ with speed $\Vtt_{\ellc}^m$; and the measurement error $\NWerr_\ell^m$ of each observation $\bar\NWobs_\ell^m$. Thus, for a road segment with maximum speed $\MaxSpeed_\ell$,
\begin{equation*}
\begin{split}
\Vtt_{\ellc}^m &\sim
   \TNormal{\NWstate_{\ellc}}{\NWstatevar_{\ellc} + \NWvar_\ell^2}{0}{\MaxSpeed_\ell}, \\
\Vttobs_{\ellc}^m &\sim
   \Normal{\Vtt_{\ellc}^m}{\NWerr_\ell^m}.
\end{split}
\end{equation*}

The network state update need therefore account for multiple observations during any single update, due to the possiblility of multiple buses completing travel along a road segment at approximately the same time. @citet:Elliott_2020; used the information filter variant of the Kalman filter to update the network state, making the inclusion of multiple sources of information a simple addition of information to the current state. The end result is an estimate of real-time traffic conditions along every road within the network, updated whenever a vehicle servicing *any* route travels along it.

The important component here is the multiple sources of error: namely the uncertainty of the state at time $t_c$, $\NWstatevar$, which increases over time with a rate of $\NWnoise$\ m/s/s; and the between-vehicle uncertainty $\NWvar_\ell$. The additional noise parameters $\NWnoise$ and $\NWvar_\ell$ are calculated from historical data using JAGS @citep:jags;.

We now have everything we need to predict arrival times based on real-time vehicle and network states, accounting for uncertainties from traffic and bus stop dwell times.
